spring:
  web:
    cors:
      allowed-origins: ${ALLOWED_ORIGINS:http://localhost:4200}  # Default to local dev
      allowed-methods: "GET,POST,PUT,DELETE"
      allowed-headers: "*"
  datasource:
    url: jdbc:sqlite:/data/database.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 60000
      busy-timeout: 15000
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: off
  liquibase:
    change-log: classpath:db/changelog/init.yaml
server:
  port: ${PORT:8080}